apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quarkbox.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "quarkbox.name" . }}-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "quarkbox.name" . }}-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "quarkbox.name" . }}-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.api.image.repository }}:{{ default .Chart.AppVersion .Values.api.image.tag }}"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: quarkbox-secrets
                  key: jwt-secret
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
